package drivers;


import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.util.zip.GZIPInputStream;

import dstructures.PlanarGraph;

public class LoadYed {

	public static void main(String[] args) throws IOException {
		if (args.length < 3)
			usage();
		int range = Integer.parseInt(args[1])-1;
		String in = args[0];
		String out = args[2];
		String extension = null;
		InputStream is = null;
		System.out.println("Loading the graphml file");
		int i = in.lastIndexOf('.');
		if (i > 0) 
		    extension = in.substring(i+1);
		 else
		 	{
			 System.err.println("Can't find file extension");
			 usage();
		 	}
		if (extension.equals("graphml")) {
			is = new FileInputStream(in);
		} else if (extension.equals("graphmlz")) {
			InputStream fis = new FileInputStream(in);
			is = new GZIPInputStream(fis);
		} else {
			 System.err.println("wrong file extension");
			 usage();
		}
		PlanarGraph graph = PlanarGraph.importYED(is, range);
		//graph.MakeGraphConnected();
		System.out.println("Saving the Graph");
		graph.SaveGraph(out);
		//graph.toCSV("orig-edges.csv", "orig-nodes.csv");
	}

	private static void usage() {
		System.out.println("Usage:\tLoadYed [inputFile] [weight range] [outputFile]");
	    System.out.println("\tload a .graphml\\z file generated by YED software");
	    System.out.println("\tYED doesn't support weigted graph so you need to supply a weigh range as well");
		System.exit(-1);
	}

}
